[platformio]
default_envs = esp32cam

[env:esp32cam]
platform = espressif32@6.9.0
board = esp32cam
framework = arduino
monitor_rts = 0
monitor_dtr = 0
lib_deps =
  esp32-camera

build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue

upload_speed = 921600
monitor_speed = 115200
# Uncomment and set these if PlatformIO cannot auto-detect your port
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
