; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
	-DFREERTOS_ENABLED
	-DCONFIG_FREERTOS_HZ=1000
	-DCORE_DEBUG_LEVEL=3
	-DBOARD_HAS_PSRAM
lib_deps = 
	ESP32Servo@^3.0.0
upload_speed = 921600
upload_port = /dev/ttyUSB1
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
monitor_filters = 
	time
	default
build_type = release
platform_packages = platformio/tool-esptoolpy@^2.40900.250804
