[platformio]
default_envs = esp32cam_s3_wroom_n16r8

[env:esp32cam_s3_wroom_n16r8]
platform = espressif32@6.9.0
board = esp32cam_s3_wroom_n16r8
framework = arduino

build_flags =
  -DBOARD_HAS_PSRAM

upload_port = /dev/ttyACM0
upload_speed = 921600

monitor_speed = 115200
